pipeline {
    agent any
    stages {
        stage('Build & Unit Test') {
            steps {
                // Runs fast unit tests (mvn test, no DB needed)
                sh 'mvn clean verify -DskipITs'
            }
        }
    }
}
