pipeline {
    agent { label 'docker-build' }
    environment {
        APP_NAME = "kiko12122/dataledge-datasource-service"
    }

    stages {
        stage('Build') {
           steps {
               dir('datasourceService'){
                   // Clean, Compile, and Package the service
                   sh './mvnw -B verify'
               }
           }
        }

        stage('SonarCloud analysis'){
            steps {
                withSonarQubeEnv(credentialsId: '7e584476-a3ff-43e1-b2b8-d9ab1436a78f', installationName: 'SonarQube Cloud'){
                    dir('datasourceService') {
                        sh '''
                            ./mvnw sonar:sonar \
                              -Dsonar.projectKey=dataledge-microservices \
                              -Dsonar.organization=dataledge-service \
                              -Dsonar.host.url=https://sonarcloud.io
                        '''
                    }
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('datasourceService'){
                    // Run specific tests
                    sh './mvnw -Dtest=*ManagerTest test'
                }
            }
        }
        
        stage('Build & Push Image') {
            steps {
                script {
                    def IMAGE_VERSION = "1.3.${env.BUILD_NUMBER}"

                    withCredentials([usernamePassword(credentialsId: 'dataledge-microservices', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        dir('datasourceService') {
                            sh "docker build -t $APP_NAME:$IMAGE_VERSION -t $APP_NAME:latest ."

                            sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"

                            sh "docker push $APP_NAME:$IMAGE_VERSION"
                            sh "docker push $APP_NAME:latest"

                            sh "docker logout"
                        }
                    }
                }
            }
        }

        stage('Deploy to Azure') {
            steps {
                withCredentials([azureServicePrincipal('dataledge-jenkins-deployer')]) {
                    sh '''
                        az login --service-principal \
                          -u $AZURE_CLIENT_ID \
                          -p $AZURE_CLIENT_SECRET \
                          -t $AZURE_TENANT_ID

                        az containerapp update \
                          --name datasource-service \
                          --resource-group Complex_Software_Dev_Environment \
                          --image kiko12122/dataledge-datasource-service:latest
                    '''
                }
            }
        }
    }
}
